import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Inter} from "next/font/google";
import "./globals.css";
import { ClerkProvider,SignInButton,SignIn,SignedIn,SignedOut,UserButton,ClerkLoaded } from "@clerk/nextjs";


const inter =Inter({ subsets: ["latin"]});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      appearance={{
        layout:{
          logoImageUrl:'/icons/yoom-logo.svg',
          socialButtonsVariant:'iconButton',
        },
        variables:{
          colorText:'#fff',
          colorPrimary:'#0E78F9',
          colorBackground:'#1c1f2e',
          colorInputBackground:'#252a41',
          colorInputText:'#fff',
        }
      }}
      
      >
      <body className={`${inter.className} bg-dark-2 ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
      </ClerkProvider>
    </html>
  );
} 
